Repository asyncer-io/r2dbc-mysql, pull requests merged in 2023-12, with the labels that each got.

#161 Correct unsigned long handling
  src/main/java/io/asyncer/r2dbc/mysql/internal/util/VarIntUtils.java
  src/main/java/io/asyncer/r2dbc/mysql/message/server/ColumnCountMessage.java
  src/main/java/io/asyncer/r2dbc/mysql/message/server/DefinitionMetadataMessage.java
  src/main/java/io/asyncer/r2dbc/mysql/message/server/LargeFieldReader.java
  src/main/java/io/asyncer/r2dbc/mysql/message/server/NormalFieldReader.java
  src/main/java/io/asyncer/r2dbc/mysql/message/server/OkMessage.java
Labels: bug, enhancement

#171 Implement `Lifecycle` for `MySqlConnection`
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnection.java
  src/test/java/io/asyncer/r2dbc/mysql/ConnectionIntegrationTest.java
Labels: enhancement

#175 Implement `Lifecycle` for `MySqlConnection` [0.9.x]
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnection.java
  src/test/java/io/asyncer/r2dbc/mysql/ConnectionIntegrationTest.java
Labels: enhancement

#172 Support for MySQL 8.2
  .github/workflows/ci-integration-tests.yml
  README.md
Labels: enhancement

#173 Remove Synchronized Statements(Loom-friendly)
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactory.java
  src/main/java/io/asyncer/r2dbc/mysql/cache/PrepareBoundedCache.java
  src/main/java/io/asyncer/r2dbc/mysql/client/RequestQueue.java
  src/main/java/io/asyncer/r2dbc/mysql/codec/DefaultCodecs.java
  src/main/java/io/asyncer/r2dbc/mysql/collation/LazyInitCharCollation.java
Labels: enhancement

#174 Remove Synchronized Statements(Loom-friendly)
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactory.java
  src/main/java/io/asyncer/r2dbc/mysql/cache/PrepareBoundedCache.java
  src/main/java/io/asyncer/r2dbc/mysql/client/RequestQueue.java
  src/main/java/io/asyncer/r2dbc/mysql/codec/DefaultCodecs.java
  src/main/java/io/asyncer/r2dbc/mysql/collation/LazyInitCharCollation.java
Labels: enhancement

#179 Enhance Transactional Methods for Improved Request Queue Handling
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnection.java
  src/test/java/io/asyncer/r2dbc/mysql/ConnectionIntegrationTest.java
Labels: bug

#180 Enhance Transactional Methods for Improved Request Queue Handling
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnection.java
  src/test/java/io/asyncer/r2dbc/mysql/ConnectionIntegrationTest.java
Labels: bug

#182 Add integration tests for MariaDB
  .github/workflows/ci-mariadb-intergration-tests.yml
  .github/workflows/ci-unit-tests.yml
  README.md
  containers/mariadb-compose.yml
  src/main/java/io/asyncer/r2dbc/mysql/ParameterWriter.java
  src/main/java/io/asyncer/r2dbc/mysql/codec/BitSetCodec.java
  src/main/java/io/asyncer/r2dbc/mysql/message/client/ParamWriter.java
  src/test/java/io/asyncer/r2dbc/mysql/IntegrationTestSupport.java
  src/test/java/io/asyncer/r2dbc/mysql/JacksonIntegrationTestSupport.java
  src/test/java/io/asyncer/r2dbc/mysql/QueryIntegrationTestSupport.java
  src/test/java/io/asyncer/r2dbc/mysql/codec/BitSetCodecTest.java
  src/test/java/io/asyncer/r2dbc/mysql/json/JacksonCodec.java
Labels: enhancement

#184 Add integration for MariaDB [0.9.x]
  .github/workflows/ci-mariadb-intergration-tests.yml
  .github/workflows/ci-unit-tests.yml
  README.md
  containers/mariadb-compose.yml
  src/main/java/io/asyncer/r2dbc/mysql/ParameterWriter.java
  src/main/java/io/asyncer/r2dbc/mysql/codec/BitSetCodec.java
  src/main/java/io/asyncer/r2dbc/mysql/message/client/ParamWriter.java
  src/test/java/io/asyncer/r2dbc/mysql/IntegrationTestSupport.java
  src/test/java/io/asyncer/r2dbc/mysql/JacksonIntegrationTestSupport.java
  src/test/java/io/asyncer/r2dbc/mysql/QueryIntegrationTestSupport.java
  src/test/java/io/asyncer/r2dbc/mysql/codec/BitSetCodecTest.java
  src/test/java/io/asyncer/r2dbc/mysql/json/JacksonCodec.java
Labels: enhancement
