Repository asyncer-io/r2dbc-mysql, pull requests merged in 2024-02, with the labels that each got.

#220 Init global variable to GitHub Actions instead of test code
  .github/workflows/ci-integration-tests.yml
  containers/mysql-compose.yml
  src/test/java/io/asyncer/r2dbc/mysql/ConnectionIntegrationTest.java
Labels: enhancement

#223 Remove `socketTimeout`
  README.md
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactory.java
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactoryProvider.java
  src/main/java/io/asyncer/r2dbc/mysql/client/Client.java
  src/test/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfigurationTest.java
  src/test/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactoryProviderTest.java
Labels: enhancement

#224 Update README
  README.md
Labels: documentation

#225 Fixed NPE with `SslMode.TUNNEL` Usage
  pom.xml
  src/main/java/io/asyncer/r2dbc/mysql/ConnectionContext.java
  src/main/java/io/asyncer/r2dbc/mysql/client/SslBridgeHandler.java
  src/test/java/io/asyncer/r2dbc/mysql/SslTunnelIntegrationTest.java
Labels: bug

#231 Correct initialization of SSL tunnel tests
  src/test/java/io/asyncer/r2dbc/mysql/SslTunnelIntegrationTest.java
Labels: bug

#230 Add support for decoding session state info
  src/main/java/io/asyncer/r2dbc/mysql/Capability.java
  src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java
  src/main/java/io/asyncer/r2dbc/mysql/message/server/OkMessage.java
  src/test/java/io/asyncer/r2dbc/mysql/message/server/OkMessageTest.java
Labels: enhancement

#232 Add LoopResources Configuration Support
  README.md
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactory.java
  src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactoryProvider.java
  src/main/java/io/asyncer/r2dbc/mysql/client/Client.java
Labels: enhancement

#234 Slim README and link to wiki
  README.md
Labels: documentation

#238 Correct an unexpected fall through
  src/main/java/io/asyncer/r2dbc/mysql/message/server/ServerMessageDecoder.java
Labels: bug

#242 Enable Leak Detection in CI Pipeline
  .github/scripts/ensure_no_leak.sh
  .github/workflows/ci-integration-tests.yml
  .github/workflows/ci-mariadb-intergration-tests.yml
  .github/workflows/ci-unit-tests.yml
  r2dbc-mysql/src/test/resources/logback-test.xml
Labels: enhancement

#240 Aligns timezone behavior with JDBC
  r2dbc-mysql/pom.xml
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/ConnectionContext.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnection.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfiguration.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactory.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactoryProvider.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/codec/CodecContext.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/codec/InstantCodec.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/codec/OffsetDateTimeCodec.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/codec/OffsetTimeCodec.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/codec/ZonedDateTimeCodec.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/internal/util/StringUtils.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/ConnectionContextTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/DateTimeIntegrationTestSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/MariaDbIntegrationTestSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/MySqlConnectionConfigurationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/MySqlConnectionFactoryProviderTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/MySqlTestKitSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/PrepareDateTimeIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/SessionStateIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/TextDateTimeIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/TimeZoneIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/codec/DateTimeCodecTestSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/codec/OffsetDateTimeCodecTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/codec/OffsetTimeCodecTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/codec/ZonedDateTimeCodecTest.java
  test-native-image/pom.xml
Labels: enhancement

#248 Correct version auto-update in workflow
  .github/scripts/upgrade_native_image_version.sh
  .github/workflows/cd-release.yml
  test-native-image/pom.xml
Labels: bug

#233 Update README and POM File
  README.md
  r2dbc-mysql/pom.xml
Labels: documentation

#250 Fix Deploy
  .github/workflows/cd-release.yml
  .github/workflows/cd-snapshot.yml
Labels: bug

#252 Correct transaction statement building
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlTransactionDefinition.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/ConnectionIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/StartTransactionStateTest.java
Labels: bug
