Repository asyncer-io/r2dbc-mysql, pull requests merged in 2024-04, with the labels that each got.

#268 Add support for SQL mode `NO_BACKSLASH_ESCAPES`
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/ConnectionContext.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/InitFlow.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/constant/ServerStatuses.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/message/client/ParamWriter.java
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/message/client/PreparedTextQueryMessage.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/ConnectionIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/QueryIntegrationTestSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/codec/CodecTestSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/codec/SetCodecTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/message/client/ParamWriterTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/message/client/ParameterWriterHelper.java
Labels: enhancement

#264 Apply TestContainer
  .github/workflows/ci-graalvm-tests.yml
  .github/workflows/ci-integration-tests.yml
  .github/workflows/ci-mariadb-intergration-tests.yml
  containers/mariadb-compose.yml
  containers/mysql-compose.yml
  r2dbc-mysql/pom.xml
  r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/message/server/ErrorMessage.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/IntegrationTestSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/JacksonIntegrationTestSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/MySqlTestKitSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/QueryIntegrationTestSupport.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/SessionStateIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/SslTunnelIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/TimeZoneIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/ZstdCompressionIntegrationTest.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/internal/util/TestContainerExtension.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/internal/util/TestServerUtil.java
  r2dbc-mysql/src/test/java/io/asyncer/r2dbc/mysql/internal/util/TestServerUtilTest.java
  r2dbc-mysql/src/test/resources/testcontainer/mysql-5.5/my.cnf
  test-native-image/src/main/java/io/asyncer/Main.java
Labels: bug, enhancement

#270 Make `upgrade_native_image_version.sh` Executable
  .github/scripts/upgrade_native_image_version.sh
Labels: bug
